### ISSUE TITLE
 Kerberos authentication is mandatory for Build and Push 

### ISSUE THREAD

**Issue by jeremiq** [voldemort/voldemort#278]
Kerberos authentication is currently required and not configurable. This makes it difficult to test  build and push jobs in any unsecured cluster. 

With all other configurations in place, build and push will fail like this: 

```
30-06-2015 17:35:20 PDT build_and_push_avro INFO - Caused by: voldemort.VoldemortException: Failed while waiting for async task (Fetch store) at node 0 to finish
30-06-2015 17:35:20 PDT build_and_push_avro INFO - 	at voldemort.client.protocol.admin.AdminClient$RPCOperations.waitForCompletion(AdminClient.java:925)
30-06-2015 17:35:20 PDT build_and_push_avro INFO - 	at voldemort.client.protocol.admin.AdminClient$RPCOperations.waitForCompletion(AdminClient.java:951)
30-06-2015 17:35:20 PDT build_and_push_avro INFO - 	at voldemort.client.protocol.admin.AdminClient$ReadOnlySpecificOperations.fetchStore(AdminClient.java:3752)
30-06-2015 17:35:20 PDT build_and_push_avro INFO - 	at voldemort.store.readonly.swapper.AdminStoreSwapper$1.call(AdminStoreSwapper.java:150)
30-06-2015 17:35:20 PDT build_and_push_avro INFO - 	at voldemort.store.readonly.swapper.AdminStoreSwapper$1.call(AdminStoreSwapper.java:145)
30-06-2015 17:35:20 PDT build_and_push_avro INFO - 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
30-06-2015 17:35:20 PDT build_and_push_avro INFO - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
30-06-2015 17:35:20 PDT build_and_push_avro INFO - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
30-06-2015 17:35:20 PDT build_and_push_avro INFO - 	at java.lang.Thread.run(Thread.java:745)
30-06-2015 17:35:20 PDT build_and_push_avro INFO - Caused by: voldemort.VoldemortException: voldemort.VoldemortException: File fetcher failed for file:/tmp/localhost/node-0 and store 'avro-custom-example-1' Reason: 
30-06-2015 17:35:20 PDT build_and_push_avro INFO - Error thrown while trying to get data from Hadoop filesystem : voldemort.VoldemortException: Error in getting Hadoop filesystem. Invalid Hadoop config directory path.
30-06-2015 17:35:20 PDT build_and_push_avro INFO - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
30-06-2015 17:35:20 PDT build_and_push_avro INFO - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
30-06-2015 17:35:20 PDT build_and_push_avro INFO - 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
30-06-2015 17:35:20 PDT build_and_push_avro INFO - 	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
30-06-2015 17:35:20 PDT build_and_push_avro INFO - 	at voldemort.utils.ReflectUtils.callConstructor(ReflectUtils.java:116)
30-06-2015 17:35:20 PDT build_and_push_avro INFO - 	at voldemort.utils.ReflectUtils.callConstructor(ReflectUtils.java:103)
30-06-2015 17:35:20 PDT build_and_push_avro INFO - 	at voldemort.store.ErrorCodeMapper.getError(ErrorCodeMapper.java:76)
30-06-2015 17:35:20 PDT build_and_push_avro INFO - 	at voldemort.client.protocol.admin.AdminClient$HelperOperations.throwException(AdminClient.java:439)
30-06-2015 17:35:20 PDT build_and_push_avro INFO - 	at voldemort.client.protocol.admin.AdminClient$RPCOperations.getAsyncRequestStatus(AdminClient.java:682)
30-06-2015 17:35:20 PDT build_and_push_avro INFO - 	at voldemort.client.protocol.admin.AdminClient$RPCOperations.waitForCompletion(AdminClient.java:886)
```

The exception is being raised here: https://github.com/voldemort/voldemort/blob/master/contrib/hadoop-store-builder/src/java/voldemort/store/readonly/fetcher/HdfsFetcher.java#L225-L233

Bad Workaround: Comment out the highlighed "if" block. 

I think the desired behavior here is probably have kerberos authentication required by default, but have an additional configuration for explicitly deactivating it.

**Comment by jeremiq** [comment]
Relatedly, when running Build and Push in an unsecured cluster, the following empty configuration must be added to the `server.properties`,

```
readonly.keytab.path=
readonly.kerberos.user=
```

without which this exception will be raised, 

```
Error thrown while trying to get data from Hadoop filesystem : voldemort.VoldemortException: Error in getting Hadoop filesystem. Invalid keytab file path.
	at voldemort.server.protocol.admin.AdminServiceRequestHandler.handleAsyncStatus(AdminServiceRequestHandler.java:1329)
	at voldemort.server.protocol.admin.AdminServiceRequestHandler.handleRequest(AdminServiceRequestHandler.java:226)
	at voldemort.server.niosocket.AsyncRequestHandler.read(AsyncRequestHandler.java:190)
	at voldemort.common.nio.SelectorManagerWorker.run(SelectorManagerWorker.java:105)
	at voldemort.common.nio.SelectorManager.run(SelectorManager.java:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: voldemort.VoldemortException: File fetcher failed for file:/tmp/localhost/node-0 and store 'avro-custom-example-1' Reason:
Error thrown while trying to get data from Hadoop filesystem : voldemort.VoldemortException: Error in getting Hadoop filesystem. Invalid keytab file path.
	at voldemort.server.protocol.admin.AdminServiceRequestHandler$4.operate(AdminServiceRequestHandler.java:1138)
	at voldemort.server.protocol.admin.AsyncOperation.run(AsyncOperation.java:33)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
```

**Comment by FelixGV** [comment]
Thanks for flagging this issue @jeremiq,

I think we should allow Voldemort to run without security if a config is specified to disable it.

-F

**Comment by FelixGV** [comment]
Would you like to take a stab at it and send a PR?

-F

**Comment by FelixGV** [comment]
Hey @jeremiq, I fixed this in #298.

You need to set ```hadoop.security.authentication=simple``` in the Hadoop config in order to disable Kerberos.

Let me know if you can give it a spin!

-F

**Comment by elad** [comment]
This isn't fixed, I just had to add this to each node's `server.properties` for BnP to work:

```
readonly.keytab.path=
readonly.kerberos.user=
```
